### ISSUE TITLE
Glob support

### ISSUE THREAD

**Issue by trainerbill** [hontas/gulp-task-loader#10]
Can we have glob support to make filtering better?  Filtering by extension won't work for me as i have some .spec.js files.  would like to be able to:

``` js
require('gulp-task-loader')('tasks/gulp/!(*.spec).js');
```

**Comment by hontas** [comment]
@trainerbill hi! sorry for the late response - just became a father and have kept away from keyboard a few weeks ;) - I'll take a look at it!

**Comment by trainerbill** [comment]
@hontas No problem, I found a different solution.  Congrats on the kiddo!

**Comment by hontas** [comment]
@trainerbill thanks :smile: - closing
