### ISSUE TITLE
Cannot properly load tasks when serving from nested directory

### ISSUE THREAD

**Issue by zaalbarxx** [hontas/gulp-task-loader#23]
Hi!
I have a problem with serving the tasks from directory that is not placed in the root of application(i.e. gulp/tasks). Basically the problem is that the tasks are not loading properly because the path to the module is not being created correctly. For example with above `dir` I get `Cannot resolve module ... \gulp\tasks\tasks\build\hello.js`. I created a fix for this altrough maybe it is not neccesary and it is just a problem for me. But you can take a look at it and eventually merge it if you'd like. I wrote the tests too, everything's passing.

**Comment by hontas** [comment]
Are you on windows? Some users have had the same problem but I haven't been able to reproduce it on my machine.

**Comment by zaalbarxx** [comment]
Yes, I am working on Windows. Maybe this is something with the path 
seperators that are different on Linux. But I have not been able to 
check it out. I think it would be a good idea that you add some 
.editorconfig to prevent behaviour such a whitespaces(it's my fault too 
obviously, but ...) :)

W dniu 2016-09-10 o 07:23, Pontus Lundin pisze:

**Comment by zaalbarxx** [comment]
The fix I created is working wel and it passes all the tests so I believe it could be merged after you test it yourself. Or we may dig deeper and try to find the cause of the problem with current code.

**Comment by hontas** [comment]
@zaalbarxx as I wrote to you in the PR, please remove all files and changes that has nothing to do with the fix. xml-files and whitespace changes.
