### ISSUE TITLE
Support for dependent tasks

### ISSUE THREAD

**Issue by chrisie** [hontas/gulp-task-loader#6]
In gulp tasks defined in gulpfile.js it is possible to define dependent tasks to specify that one task must complete before another begins (see the final example here https://github.com/gulpjs/gulp/blob/master/docs/API.md#async-task-support).
Is this somehow supported for tasks created in the gulp-tasks folder?

**Comment by tteltrab** [comment]
@chrisie you can use [gulp-run-sequence](https://github.com/OverZealous/run-sequence) to accomplish that.  You task could look something like:

```
var runSequence = require("run-sequence"),
    paths = require("./lib/config")().paths;

require("gulp-task-loader")();

gulp.task("test", function () {
    runSequence("webpack",
        ["lint", "crawl", "mocha-test"]);
});
```

(in this example webpack is run first and then lint, crawl, and mocha-test are run in parallel).

I think what you're looking for is probably outside of the scope of this project.

**Comment by hontas** [comment]
@chrisie It is supported in gulp and will work in gulp-task-loader.
Simply use one of the described ways in the link you posted. Callback, Promise or stream.

All that gulp-task-loader does is to wrap the function you export in gulp.task() and gives it the name of the file. Quite simple really.

To take the example from the docs:

``` js
// gulp-tasks/jekyll.js
var exec = require('child_process').exec;
module.exports = function(cb) {
  exec('jekyll build', function(err) {
    if (err) {
      return cb(err); // return error
    }
    cb(); // finished task
}
```
