### ISSUE TITLE
add file filter 

### ISSUE THREAD

**Issue by fxck** [hontas/gulp-task-loader#8]
I'm working on something over vpn/samba, and my mac is creating these http://apple.stackexchange.com/a/14981/87168 which then gulp-task-loader is trying to load and obviously fails with `SyntaxError: Unexpected token ILLEGAL` DIt would be nice if you could define some sort of filter in options.

**Comment by fxck** [comment]
perhaps something like this https://gist.github.com/fxck/595149be34999dd59069/revisions?diff=unified

**Comment by hontas** [comment]
There is already a filter in place for file extension - see readme: https://github.com/hontas/gulp-task-loader#extensions. Try that first. Closing this for now. Cheers.
